# Generated by Django 6.0.2 on 2026-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='Espèces', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(default='Coupe simple', max_length=255),
        ),
    ]
