# Generated by Django 6.0.2 on 2026-03-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_payment_method_transaction_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(default='', max_length=255),
        ),
    ]
